AWSTemplateFormatVersion: '2010-09-09'
Description:
  "Creates an Elastic IP address which can then be attached to an EC2 instance"
Resources:
  ipAddress:
    Type: AWS::EC2::EIP
    Properties: 
      Domain: vpc
Outputs:
  ipAddress:
    Description: IP Address (referenced via the id)
    Value:
      Ref: ipAddress
  ipAddressAllocationId:
    Description: IP Address AllocationId used for associating this EIP to an EC2 instance
    Value: 
      Fn::GetAtt:
        - ipAddress
        - AllocationId