AWSTemplateFormatVersion: '2010-09-09'
Description:
  "Creates an AWS subnet on a virtual private cloud (VPC)"
Parameters:
  Name: 
    Type: String
    Description: Name of the subnet
  VpcId:
    Type: String
    Description: ID of the VPC network
  AddressSpace:
    Type: String
    Description: Address space for the subnet
Resources:
  subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VpcId
      CidrBlock:
        Ref: AddressSpace
      Tags:
        - Key: Name
          Value:
            Ref: Name
Outputs:
  id:
    Description: id of the subnet
    Value:
      Ref: subnet